version: 0.2

env:
  variables:
    JEKYLL_ENV: "production"

phases:
  install:
    runtime-versions:
      ruby: 2.7
      nodejs: 10
    commands:
      # - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
      # - export NVM_DIR="$HOME/.nvm"
      # - bash -c "source $HOME/.nvm/nvm.sh && echo 'yes' || echo 'no' ; nvm install 10"
      # - bash -c "source $HOME/.nvm/nvm.sh && nvm install 10 && npm i"
      - npm i
      - bundle config set path './.bundle-gems'
      - bundle install
  build:
    commands:
      # - bash -c "source $HOME/.nvm/nvm.sh && npm run build"
      - npm run build
      - aws s3 sync --delete --acl public-read ./_site s3://flux-party-website/
      - aws cloudfront create-invalidation --distribution-id $CDN_DISTRIBUTION_ID --paths "/*"
  post_build:
    commands: []
cache:
  paths:
    - node_modules
    - .bundle
    - .bundle-gems
